version: "3.8"

services:
    messaging:
           image: 'rabbitmq:3.8.8-management'
           environment:
             RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
             RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
             RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
           ports:
               - 15672:15672
    adminer:
        image: adminer
        ports:
             - 8080:8080
    db:
           build: db/
           command: --default-authentication-plugin=mysql_native_password
           restart: always
           ports: 
                - "3306:3306"
           environment:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           volumes:
                - data-volume:/var/lib/mysql
    front-end:
           build: front-end/
           ports:
               - 5000:5000
    back-end: 
           build: back-end/
volumes:
     data-volume:
