version: "3.8"

services:
    messaging:
           image: 'rabbitmq:3.8.8-management'
           ports:
               - 15672:15672
    db:
           build: db/
           command: --default-authentication-plugin=mysql_native_password
           restart: always
           environment:
                MYSQL_ROOT_PASSWORD: 'example'
           volumes:
                - data-volume:/var/lib/mysql
    front-end:
           build: front-end/
           ports:
               - 5000:5000
    back-end: 
           build: back-end/
volumes:
     data-volume:
