CREATE DATABASE users
CREATE TABLE user (
name VARCHAR(20),
password VARCHAR(255)
);
INSERT INTO user VALUES ("Alice","123");
INSERT INTO user VALUES ("Bob","123");
INSERT INTO user VALUES ("Carol","123");
